#include<stdio.h>
#include<conio.h>
#include<math.h>
void main()
{
	printf("floor=%f",floor(3.6));
	printf("\nceil=%f",ceil(2.5));
	printf("\nsin=%f",sin(5.5));
	printf("\ncosh=%f",cosh(5.3));
	printf("\nexp=%f",exp(2.1));
	printf("\ntan=%f",tan(31.1));
	printf("\ntanh=%f",tanh(4.2));
	printf("\nsinh=%f",sinh(4.1));
	printf("\nlog=%f",log(5.2));
	printf("\nlog10=%f",log10(1.3));
	printf("\nsqrt=%f",sqrt(3.9));
	printf("\npow=%f",pow(2.3,2.7));
	printf("\ntrunc=%f",trunc(2.8));
	printf("\nabs=%f",abs(6.7));	
}
